PyISY/Nodes/__init__.py, PyISY/Nodes/node.py
There may be more uom codes than I have - but these are the ones that I know about.
Pull out the `uom` field and split by / character or use the dictionary for custom measurements (examples: Locks, Barrier, Energy Meter, etc.)
Pull out `prec` field for analog sensor precision - for example, energy meter has 2 units of precision, so 500.00 Watts comes through as `50000` - this will help consumers of the library to know where to place the decimal in the value dynamically.
=> Parse out Unit of Measure and Precision

PyISY/Connection.py, PyISY/Nodes/__init__.py, PyISY/Nodes/node.py, PyISY/Programs/folder.py
For now, I'm sort of hacking your library to get locks to work in HASS..
``` python
def lock(self, **kwargs) -> None:
"""Lock the device."""
req_url = self._conn.compileURL(['nodes', self.unique_id, 'cmd',
'SECMD', '1'])
response = self._conn.request(req_url)
if response is None:
_LOGGER.error('Unable to lock device')
self._node.update(0.5)
def unlock(self, **kwargs) -> None:
"""Unlock the device."""
req_url = self._conn.compileURL(['nodes', self.unique_id, 'cmd',
'SECMD', '0'])
response = self._conn.request(req_url)
if response is None:
_LOGGER.error('Unable to lock device')
self._node.update(0.5)
```
Also added support for aux. properties (battery level, humidity, set points, etc.) and now the commands for climate (thermostats)!
=> Locks use a different command

PyISY/Nodes/__init__.py
Removing the filter based on family as per the discussion in #27
I've tested this using Home Assistant, which will now successfully import the groups/scenes.
I also slightly changed the logic for how the root node is detected, using a bitmask check rather than checking for an exact integer value, which will be more accurate in the event that the root node gets a new flag added to it.
=> Remove family filter that was blocking all scenes from getting nodes

PyISY/Events/events.py, PyISY/Events/eventsSSL.py, PyISY/Nodes/__init__.py, PyISY/Nodes/node.py
This adds quick and dirty support for emitting "control" events from the ISY event stream out to subscribers via the nodes associated with the control events.
The primary use case I am trying to solve with this is allowing Home Assistant to be aware of button presses on switches, not just when a light state changes. This will allow creating special automations for when buttons are double-pressed, or even using an Insteon controller (such as the 8-button remote) without it needing to be linked to any actual devices in the Insteon network.
It will ALSO open the door to properly handling heartbeats, which are always "on" events. Since they never emit an "off", the events never make it out to Home Assistant.
Implements #33
=> Pass control events to nodes for emitting to subscribers

PyISY/Nodes/__init__.py, PyISY/Nodes/node.py
**Note: this PR is branched off of PR #35, and should be merged after**
This simply adds a few more attributes to the Node object that come from the ISY's payload that I needed when improving the ISY994 support in Home Assistant:
* `nid` is the node id. It was only available in a protected property before. This was added mainly because of the parent_nid use-case below.
* `node_def_id` is the NodeDefId introduced in the 5.x builds of the ISY firmware. They make determining the broad type of device such as dimmer, relay, sensor very convenient.
* `parent_nid` is the parent node - this only applies when a single device uses multiple nodes (like sensors, keypads, and multi-button remotes). In addition to exposing the `parent_nid` string, there is also a `parent_node` property that will return …
=> Expose more params

PyISY/Nodes/node.py
There is a very distinct difference between _blank_ values and 0 values as reported by the ISY.
Blank values are used when the ISY does not know the status of a node, such as in cases where a battery-powered sensor has not reported a state since the ISY last booted up. The current implementation would cause leak sensors, for example, to report as WET (the dry node would be 0).
This change makes the value be -1 to hopefully reduce the magnitude of breaking change that this could be, while still allowing consuming applications to treat UNKNOWN values as different than OFF. (I didn't want to go so far as to make the Value sometimes be a non-integer.) Still, I would recommend a minor version number update to indicate the potential breaking change.
=> Set node value to -1 when ISY reports it as unknown (blank string)

PyISY/ISY.py
Using `.get()` avoids KeyError when `configuration['Weather Information']` is not set.
=> use .get() instead of key name to avoid KeyError when key not set

PyISY/__init__.py, setup.py
Removed deprecated download_url (which was 404 anyway) and added the long_description which pulls from the README per Python docs
=> 1.1.2 version bump and setup.py cleanup

PyISY/Nodes/__init__.py, PyISY/Nodes/node.py
As per shbatm#13, there are some nodes that do not provide a unit of measurement or precision when they are initially queried, but will eventually provide these in a status update. This change allows these to be "reset" if they change or are set after the initial query.
=> [V2] Allow updating precision and UOM if they change

PyISY/Programs/__init__.py, PyISY/Variables/__init__.py, PyISY/clock.py, PyISY/connection.py, PyISY/constants.py, PyISY/helpers.py, PyISY/isy.py
Add a Clock class with the following properties exposed from the `/rest/time` endpoint:
- last_called: the time of the last call to /rest/time
- tz_offset: The Time Zone Offset of the ISY
- dst: Daylight Savings Time Enabled or not
- latitude: ISY Device Latitude
- longitude: ISY Device Longitude
- sunrise: ISY Calculated Sunrise
- sunset: ISY Calculated Sunset
- military: If the clock is military time or not.
The new class is used within PyISY primarily to determine if the ISY is using Military (24-hr) time or not. The new properties are exposed at `isy.clock` for external use and can be updated by calling `isy.clock.update()`. There is currently no automatic/periodic updating of this class and there are no automatic events received.
=> [V2] Add ISY Clock and Location Information

CHANGELOG.md, PyISY/configuration.py, PyISY/isy.py
Expose the hostname as `isy.hostname`.
Expose the UUID and Firmware from the existing Configuration call:
- isy.configuration.firmware
- isy.configuration.uuid
Update CHANGELOG
Note: this is setup for supporting multiple ISY controllers. Currently, there is no easy way to differentiate which ISY an individual Node class is attached to.
=> [V2] Expose Firmware, UUID, and Hostname properties

PyISY/Nodes/__init__.py, PyISY/Programs/__init__.py, PyISY/Variables/__init__.py, PyISY/climate.py, PyISY/events.py
Rename _upmsg, _routemsg, _controlmsg to more descriptive names.
Also made public (removed `_` prefix) to make Lint happy since these are called externally in `events.py`.
=> [V2] Rename message functions to be more descriptive.

CHANGELOG.md, pyisy/constants.py, pyisy/helpers.py, pyisy/isy.py, pyisy/nodes/node.py, pyisy/nodes/nodebase.py, pyisy/programs/folder.py, pyisy/programs/program.py
Backtracking and reverting the changes made in #44 to dynamically add control functions to nodes and programs at run-time. 
The purpose of the original change was to reduce redundant code, and enable future blocking of certain commands from being run on devices that didn't support it (e.g. don't add the lock/unlock functions to a thermostat)--in reality, the dynamic functions just hurt readability of the code and makes it harder for others to integrate this module into other projects.
Instead, this change adds back the individual functions in a cleaner manner than V1 and adds the `node.is_thermostat` and `node.is_lock` properties for some known (easy) categories/sorting and shows warnings when trying to call commands on the incorrect type of device.
=> [V2] Revert previous V2 change to dynamically add node commands

CHANGELOG.md, pyisy/nodes/__init__.py, pyisy/nodes/group.py, pyisy/nodes/node.py, pyisy/nodes/nodebase.py
Previously only the physical "Parent" node was exposed if it existed. This change exposes the "Primary" (corrected name from ISY WSDK) node address, regardless of if it is different from the node address or not (for most devices, the primary node is the same).  The "Parent" node is still returned the same as it previously was, as it is still useful to have access to the primary node's object and functions for things like motion sensors and leak detection. This will also be important if Z-Wave compatibility is expanded, since the ISY likes to break up Z-Wave devices into multiple sub-nodes.
Sets up for Device Grouping in Home Assistant as well as future solution to automacus/PyISY#11
=> [V2] Better handling of Parent and Primary Node properties

.pre-commit-config.yaml, README.md, pyisy/__init__.py, pyisy/configuration.py, pyisy/connection.py, pyisy/events.py, pyisy/helpers.py, pyisy/networking.py, pyisy/nodes/__init__.py, pyisy/nodes/node.py, pyisy/programs/__init__.py, pyisy/programs/folder.py, requirements-dev.txt, setup.cfg, setup.py
This adds `pre-commit` tests and repos for `black`, `isort`, `flake8`, and `codespell`.
To use:
```shell
pip install pre-commit
pre-commit install
pre-commit run --all-files
```
=> [V2] Add Pre-Commit Config for Black, iSort, Flake8, and Codespell

CHANGELOG.md, pyisy/constants.py, pyisy/nodes/__init__.py, pyisy/nodes/handlers.py, pyisy/nodes/node.py
- Return the manufacturer string and full details for Z-Wave Devices in a ZWaveProperties class.
- Include references for Node Categories and Z-Wave Dev Type Categories
- Add color bulbs to "dimmable" property.
- Add missing units of measure and control names for ISYv5
=> [V2] Expose a host of Z-Wave Properties

pyisy/clock.py, pyisy/constants.py, pyisy/helpers.py, pyisy/networking.py, pyisy/nodes/__init__.py, pyisy/nodes/node.py, pyisy/nodes/nodebase.py, pyisy/programs/__init__.py, pyisy/variables/__init__.py
- Make all status and property values return integers instead of sometimes integer, sometimes string.
- Use a constant for the XML Parsing Error types, and include ExpatError
- Use nested errors instead of raising a new error inside of an error handler.
=> [V2] Improved Consistency in Error Handling, Fix Type Inconsistency

pyisy/networking.py, pyisy/nodes/__init__.py, pyisy/programs/__init__.py, pyisy/programs/program.py, pyisy/variables/__init__.py
Eliminate the use of Class variables in favor of Instance Variables. Using Class Variables for the navigator classes causes an issue when multiple ISYs are in use.  Only one instance of PyISY is loaded, so it attempt to share the same lists for all instances of the ISY class. When multiple ISYs are connected in the same program, this causes errors.
=> [V2] Use Instance instead of Class Variables To Support Multiple ISYs

.gitignore, .vscode/settings.json, CHANGELOG.md, pyisy/constants.py, pyisy/events.py, pyisy/isy.py, pyisy/nodes/__init__.py
Add connection events for the Event Stream to allow subscription and callbacks. Attach a callback with `isy.connection_events(callback)` and receive a string with the event detail. See `constants.py` for events starting with prefix `ES_`.
This will allow detection and response in a subscriber to the different events, rather than just relying on the logs only.
=> Add connection events target

pyisy/nodes/nodebase.py
Missed a change when we updated PR #94 to use `address` instead of `node`
=> Hotfix incorrect keyword argument in query func

pyisy/nodes/node.py, pyisy/nodes/nodebase.py
ISYv4 firmware sends blank UOMs in the event updates, which can cause issues if it overwrites a known, valid UOM.
This should resolve the issue home-assistant/core#37537 once a new package is published.
=> Guard against overwriting known attributes with blanks

.devcontainer/Dockerfile, .devcontainer/devcontainer.json, .devcontainer/postCreate.sh, .gitignore, .pre-commit-config.yaml, .vscode/extensions.json, .vscode/settings.json, README.md, examples/connection_test.py, pyisy/connection.py, pyisy/eventreader.py, pyisy/events.py, pyisy/nodes/node.py, pyisy/programs/program.py, pyisy/variables/variable.py, requirements-dev.txt, requirements.txt, setup.py
- Add a VSCode Devcontainer based on Python 3.8
- Update the package requirements to explicitly include `dateutil` and the dev requirements for `pre-commit`
- Add `pyupgrade` hook to `pre-commit` and run it on the whole repo.
Tested on VSCode, Docker on Windows 10.
Tag @OverloadUT
=> Add Devcontainer, Update Requirements, Use PyUpgrade

pyisy/events.py
Fixes #109 by resolving the depreciation warning isAlive() 
```
2020-06-22 15:15:51,271 Thread-2   py.warnings        WARNING  warnings:_showwarnmsg: /var/polyglot/.local/lib/python3.7/site-packages/pyisy/events.py:113: PendingDeprecationWarning: isAlive() is deprecated, use is_alive() instead
```
=> Fix #109 - Update for events depreciation warning

examples/connection_test.py, pyisy/clock.py, pyisy/configuration.py, pyisy/connection.py, pyisy/constants.py, pyisy/events.py, pyisy/helpers.py, pyisy/isy.py, pyisy/networking.py, pyisy/nodes/__init__.py, pyisy/nodes/node.py, pyisy/nodes/nodebase.py, pyisy/programs/__init__.py, pyisy/programs/folder.py, pyisy/variables/__init__.py, pyisy/variables/variable.py
This removes the `log=` parameter when initializing new `Connection` and `ISY` class instances. Please update any loading functions you may use to remove this `log=` parameter.
General cleanup of all logging.
Removes reliance on `isy` parent objects to provide logger and uses a module-wide `_LOGGER`.  Everything will be logged under the `pyisy` namespace except Events. Events maintains a separate logger namespace to allow targeting in handlers of `pyisy.events`.
=> Logging cleanup and consolidation

pyisy/constants.py, pyisy/nodes/node.py
- `Node.dimmable` has been depreciated in favor of `Node.is_dimmable` to make the naming more consistent with `is_lock` and `is_thermostat`. `Node.dimmable` will still work, however, plan for it to be removed in the future.
- `Node.is_dimmable` will only include the first subnode for Insteon devices in type 1. This should represent the main (load) button for KeypadLincs and the light for FanLincs, all other subnodes (KPL buttons and Fan Motor) are not dimmable (fixes #110)
- Revise `is_lock`, `is_thermostat`, and `is_lock` properties of the Node class to be more consistent.
- Use string literals for special Insteon types
- Using the `is_dimmable` property of a node is not considered reliable. As of Version 2, there is no truly reliable "sorting" of device types within the PyISY module …
=> Revise Node.dimmable property to exclude non-dimmable subnodes

pyisy/connection.py, pyisy/eventreader.py
Use UTF-8 encoding and ignore any errors when decoding the responses from Requests and from the event stream.
Related issue #124 - Fixes issue for V2.
cc: @bdraco
=> Force UTF-8 decoding of responses and ignore errors

pyisy/nodes/__init__.py
Blank status values should be initially translated from the ISY as empty strings for consistency between the initial loading (`helpers.py`) and the events received in `nodes`.
In addition, failing to set a default causes a casting error trying to cast `int(None)`.
=> Fix casting error on blank status sent during event

pyisy/connection.py, pyisy/events/websocket.py
Use UTF-8 encoding and ignore any errors when decoding the responses from Requests and from the event stream.
Related issue #124 - Fixes issue for V3
Needs to be tested to confirm no breaking changes before merge.
cc: @bdraco
=> [V3] Force UTF-8 decoding of responses and ignore errors

pyisy/nodes/__init__.py, pyisy/nodes/nodebase.py
Exposes a `node.folder` property for each node and group to get the name of the folder containing the node or group of nodes.
Exposes `nodes.get_folder(address)` function on the node manager for the same purpose.
=> Expose Folder Property for Groups and Nodes

pyisy/nodes/__init__.py, pyisy/nodes/nodebase.py
Expose a folder property for each node and group to be accessible from within the node--without having to parse the entire Nodes tree.
Exposes a `node.folder` property for each node and group to get the name of the folder containing the node or group of nodes.
Exposes `nodes.get_folder(address)` function on the node manager for the same purpose.
=> Add a folder property to each node and group

CHANGELOG.md, pyisy/constants.py, pyisy/nodes/nodebase.py
Adds support for renaming Nodes and Groups on the ISY from within PyISY.
Fixes #129.
=> Allow renaming of nodes and groups

CHANGELOG.md, pyisy/constants.py, pyisy/nodes/group.py
Group/Scene Status now excludes the state of any Insteon battery powered devices (on ISYv5 firmware only). These devices often have stale states and only update when they change, not when other controllers in the scene change; this leads to incorrect or misleading Group/Scene states.
This applies to ISYv5 firmware only because only the `NodeDefID` property is used to identify battery powered devices; this is to prevent the need for `startswith()` lookups for device types (used in ISYv4 where `NodeDefID`'s are not available), which would cause additional minor performance issues whenever a group status needs to be updated.
Fixes #153.
=> Exclude Insteon battery-powered device states from Group/Scene status

pyisy/helpers.py
Same as #248, but for 3.x
Fixes https://github.com/home-assistant/core/issues/66003
=> Guard against downstream errors interrupting the socket connection

.pre-commit-config.yaml, CHANGELOG.md, pyisy/constants.py, pyisy/nodes/group.py
-   Fix Group States for Stateless Controllers (Fixes #256) (#257)
-   Battery Operated, ControlLinc and RemoteLinc (v1) devices are excluded from group states to correctly reflect the state since these devices don't update the controller status unless a button is pushed.
=> [v2.1.5] - Fix Group States for Stateless Controllers

pyisy/nodes/group.py
The group modules created a task in __init__ which
can be avoided since nothing is being awaited in
the update
=> Reduce task creation at startup
